# Generated by Django 3.2.15 on 2022-08-24 21:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Etiquetas',
            fields=[
                ('etiqueta', models.CharField(max_length=50)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name_plural': 'Etiqueta',
            },
        ),
        migrations.CreateModel(
            name='Publicaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Titulo', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('imagen', models.CharField(max_length=200)),
                ('icono', models.CharField(max_length=150)),
                ('fecha', models.DateField()),
            ],
            options={
                'verbose_name_plural': 'Publicaciones',
            },
        ),
        migrations.CreateModel(
            name='Proyectos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Titulo', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('imagen', models.CharField(max_length=200)),
                ('lugar', models.CharField(max_length=100)),
                ('recuado', models.IntegerField()),
                ('donativos', models.IntegerField()),
                ('icono', models.CharField(max_length=150)),
                ('fecha', models.DateField()),
                ('etiquetas', models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='proyectos_socias.etiquetas')),
            ],
            options={
                'verbose_name_plural': 'Proyectos',
            },
        ),
    ]
