# Generated by Django 3.2.15 on 2022-08-24 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos_socias', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etiquetas',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
