# Generated by Django 3.2.15 on 2022-08-29 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos_socias', '0002_alter_etiquetas_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proyectos',
            old_name='recuado',
            new_name='recaudo',
        ),
    ]
