# Generated by Django 3.2.15 on 2022-08-30 23:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
        ('proyectos_socias', '0003_rename_recuado_proyectos_recaudo'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyectos',
            name='usuarios',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuariosociasmodel'),
        ),
    ]
