# Generated by Django 3.2.15 on 2022-08-31 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos_socias', '0005_auto_20220831_0957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorias',
            name='icono',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
