# Generated by Django 3.2.15 on 2022-08-31 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos_socias', '0006_alter_categorias_icono'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categorias',
            options={'verbose_name_plural': 'Categorias'},
        ),
    ]
