# Generated by Django 3.2.15 on 2022-09-02 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos_socias', '0008_auto_20220902_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyectos',
            name='nombre',
            field=models.CharField(help_text='Nombre del emprendimiento', max_length=100),
        ),
    ]
