# Generated by Django 3.2.15 on 2022-09-02 20:43

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
        ('proyectos_socias', '0009_alter_proyectos_nombre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proyectos',
            name='lugar',
        ),
        migrations.AddField(
            model_name='proyectos',
            name='ciudad',
            field=models.CharField(blank=True, help_text='ciudad donde está el proyecto', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='proyectos',
            name='aportes',
            field=models.IntegerField(blank=True, help_text='la cantidad de aportes que le han hecho a su proyecto', null=True),
        ),
        migrations.AlterField(
            model_name='proyectos',
            name='categoria',
            field=models.ForeignKey(blank=True, help_text='Categorias a las cuales se posa el proyecto', null=True, on_delete=django.db.models.deletion.CASCADE, to='proyectos_socias.categorias'),
        ),
        migrations.AlterField(
            model_name='proyectos',
            name='etiquetas',
            field=models.ForeignKey(blank=True, default=1, help_text='etiquetas del proyecto', on_delete=django.db.models.deletion.CASCADE, to='proyectos_socias.etiquetas'),
        ),
        migrations.AlterField(
            model_name='proyectos',
            name='fecha_creacion_empresa',
            field=models.DateField(blank=True, help_text='Fecha en la que se creó o se fundó la empresa', null=True),
        ),
        migrations.AlterField(
            model_name='proyectos',
            name='fecha_creacion_socias',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 9, 2, 15, 43, 30, 178285), help_text='Fecha en la que creó el proyecto en Socias, por defecto', null=True),
        ),
        migrations.AlterField(
            model_name='proyectos',
            name='monto_total',
            field=models.IntegerField(blank=True, help_text='Monto total que pide para la empresa', null=True),
        ),
        migrations.AlterField(
            model_name='proyectos',
            name='usuarios',
            field=models.ForeignKey(blank=True, help_text='Usuario que creoó el proyecto', null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuariosociasmodel'),
        ),
    ]
