# Generated by Django 3.2.15 on 2022-09-07 16:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos_socias', '0010_auto_20220902_1543'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publicaciones',
            old_name='Titulo',
            new_name='titulo',
        ),
        migrations.AlterField(
            model_name='proyectos',
            name='fecha_creacion_socias',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 9, 7, 11, 31, 17, 234563), help_text='Fecha en la que creó el proyecto en Socias, por defecto', null=True),
        ),
    ]
