# Generated by Django 3.2.15 on 2022-09-08 21:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos_socias', '0011_auto_20220907_1131'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyectos',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='proyectos',
            name='fecha_creacion_socias',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 9, 8, 16, 31, 8, 262432), help_text='Fecha en la que creó el proyecto en Socias, por defecto', null=True),
        ),
    ]
