# Generated by Django 3.2.15 on 2022-09-08 21:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos_socias', '0014_alter_proyectos_fecha_creacion_socias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyectos',
            name='fecha_creacion_socias',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 9, 8, 16, 37, 28, 817718), help_text='Fecha en la que creó el proyecto en Socias, por defecto', null=True),
        ),
    ]
